### ISSUE TITLE
Check if output directory exists and is writable before starting

### ISSUE THREAD

**Issue by watery** [dubek/rabbitmq-dump-queue#11]
This is a small improvement request, but I've noticed that (on Windows at least) if the directory specified in the `-output-dir` parameter does not exist, a write error is printed (I guess) when trying to dump the first message:

    Save message: open tmp/msg-0000: Cannot find the specified path

It would be better if a check of directory existence / writeability be done before even starting to process queue messages.

**Comment by dubek** [comment]
I see that standard Linux comands (`cp`) behave like this:

```
$ cp file1 file2 file3 /tmp/non-existing-dir/
cp: target '/tmp/non-existing-dir/' is not a directory

$ cp file1 file2 file3 /tmp/read-only-dir/
cp: cannot create regular file '/tmp/read-only-dir/file1': Permission denied
cp: cannot create regular file '/tmp/read-only-dir/file2': Permission denied
cp: cannot create regular file '/tmp/read-only-dir/file3': Permission denied
```

So the tool does check that the target is a directory, but doesn't check for permissions in it (which makes sense to me). 

Do you expect a clearer error message when the output directory doesn't exist?

**Comment by dubek** [comment]
(inactive issue; closing.)
