### ISSUE TITLE
Ability to ignore invalid certificate

### ISSUE THREAD

**Issue by robmoore** [dubek/rabbitmq-dump-queue#5]
I'm trying to connect to an instance with a self-signed cert using `amqps://...` and am receiving the following error:

`Dial: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs`

It would be handy to have a means to skip certificate validation or just log if there's an issue.

**Comment by dubek** [comment]
Thanks for the suggestion. Indeed I haven't dealt with any TLS-related options, like setting the known CAs and setting client-side certificate (+key).

I'll try to add at least the option to (insecurely) ignore TLS errors (like hostname mismatch, expired certs, unknown issuer CA).

**Comment by dubek** [comment]
@robmoore Can you please try the code from git branch `tls-insecure` ? I added an optional `-insecure-tls` switch which should instruct the TLS layer to skip certificate verification. Let me know if it solves the issue you encountered.

**Comment by robmoore** [comment]
It works! Thanks for implementing this.

**Comment by dubek** [comment]
This is now part of the v0.3 release.

Thanks @robmoore for suggesting and helping to test.
