### ISSUE TITLE
Argument parsing

### ISSUE THREAD

**Issue by msteggink** [dubek/rabbitmq-dump-queue#6]
There seems to be a minor issue with parsing the arguments.

 ./rabbitmq-dump-queue -uri 'REDACTED' -queue=logging -max-messages=50 -output-dir /root/ 

Dumps 50 messages as expected:
/root/msg-0000
...
/root/msg-0049

Now note the space with an character after the queue parameter.
 ./rabbitmq-dump-queue -uri 'REDACTED' -queue=logging x -max-messages=50 -output-dir /root/
msg-0000
...
msg-0999

Which dumps 1000 messages in my current working directory as per the defaults. It only occurs with the queue parameter.

It does not occur when the queue parameter is given at the end.

 ./rabbitmq-dump-queue -uri 'REDACTED' -max-messages=50  -output-dir /root/ -queue=logging x

**Comment by dubek** [comment]
Thank you @msteggink for reporting this!

Please try the current master (5e4c580f66022c40ed7f88acd7e17f8163e0049e) which I just pushed. Hopefully solves this issue — it exits with error if command-line includes any non-switch argument.

**Comment by msteggink** [comment]
Works like a charm, thanks for adding the error catch.
